[package]
name = "vortex-file"
version = { workspace = true }
description = "Vortex file readers and writers"
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
include = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
categories = { workspace = true }
readme = "README.md"

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
flatbuffers = { workspace = true }
futures = { workspace = true, features = ["std"] }
# Needed to pickup the "wasm_js" feature for wasm targets from the workspace configuration
getrandom_v03 = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
moka = { workspace = true, features = ["future", "quanta"] }
oneshot = { workspace = true, features = ["async"] }
rustc-hash = { workspace = true }
tokio = { workspace = true, features = ["rt"], optional = true }
tracing = { workspace = true, optional = true }
tracing-futures = { workspace = true, features = ["futures-03"], optional = true }
# Needed to pickup the "js" feature for wasm targets from the workspace configuration
uuid = { workspace = true }
vortex-alp = { workspace = true }
vortex-array = { workspace = true }
vortex-btrblocks = { workspace = true }
vortex-buffer = { workspace = true }
vortex-bytebool = { workspace = true }
vortex-datetime-parts = { workspace = true }
vortex-dict = { workspace = true }
vortex-dtype = { workspace = true }
vortex-error = { workspace = true }
vortex-expr = { workspace = true }
vortex-fastlanes = { workspace = true }
vortex-flatbuffers = { workspace = true, features = ["file"] }
vortex-fsst = { workspace = true }
vortex-io = { workspace = true }
vortex-layout = { workspace = true }
vortex-metrics = { workspace = true }
vortex-runend = { workspace = true }
vortex-sparse = { workspace = true }
vortex-zigzag = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
vortex-array = { workspace = true, features = ["test-harness"] }
vortex-io = { path = "../vortex-io", features = ["tokio"] }

[lints]
workspace = true

[features]
object_store = ["vortex-error/object_store", "vortex-io/object_store"]
tracing = ["dep:tracing", "dep:tracing-futures", "vortex-io/tracing", "vortex-layout/tracing"]
