[package]
name = "vortex-buffer"
authors = { workspace = true }
categories = { workspace = true }
description = "A byte buffer implementation for Vortex"
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[features]
arrow = ["dep:arrow-buffer"]
compio = ["dep:compio"]
default = []
warn-copy = ["dep:log"]

[dependencies]
arrow-buffer = { workspace = true, optional = true }
bytes = { workspace = true }
compio = { workspace = true, optional = true }
log = { workspace = true, optional = true }
num-traits = { workspace = true }
vortex-error = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
arrow-buffer = { workspace = true }
divan = { workspace = true }

[[bench]]
name = "vortex_buffer"
harness = false
